"""add transaction_date to transactions

Revision ID: 7ea02b8cbb0c
Revises: 99f4ccb763c0
Create Date: 2026-06-19 06:38:48.995858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea02b8cbb0c'
down_revision: Union[str, Sequence[str], None] = '99f4ccb763c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
